### ISSUE TITLE
Segmentation

### ISSUE THREAD

**Issue by leonardcser** [leonardcser/waldo-footage-segmenter#6]
Create the segmentation module that takes as input a json file, and trims the footage into small clips.

**Approaches:**
- MoviePy (https://pypi.org/project/moviepy/)
- OpenCV

**Proposed output:**
<pre>
- /out
  - /video_id
    - clip1_id.mp4
    - clip2_id.mp4
    - ...
    - meta.json
</pre>

**Tasks:**

- [ ] Read mp4 video file
- [ ] Read json file
- [ ] Trim video & save clips
- [ ] Create test cases
